FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 5003

ENV FLASK_ENV=production

CMD ["python", "sentiment_analysis_service.py"]
