FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

EXPOSE 5005

ENV FLASK_ENV=production

CMD ["python", "pipe_and_filter_service.py"]
